org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseG1GC -XX:+UseStringDeduplication -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.configureondemand=false
org.gradle.caching=false
org.gradle.daemon=false
org.gradle.vfs.watch=false
android.useAndroidX=true
android.enableJetifier=true
android.enableR8.fullMode=true
kotlin.code.style=official
kotlin.incremental=false
kotlin.incremental.android=false
kotlin.incremental.java=false
kotlin.caching.enabled=false
kotlin.build.report.output=file
org.gradle.workers.max=2
org.gradle.logging.level=info
android.enableAapt2Daemon=false
