export const APP_CONFIG = {
  name: "DX Play",
  fullName: "DebridXtream IPTV",
  version: "3.0.6",
  versionCode: 30,
  apkSize: "13.1 MB",
  downloaderCode: "4282574",
  downloadUrl: "/downloads/DebridXtream-latest.apk",
  companionUrl: "/link",
  resellerPortalUrl: "/reseller/login",
  accountUrl: "/account",
  telegramSupport: "https://t.me/debridxtream",
  whatsappSupport: "https://wa.me/message/DXPLAY",
  tagline: "The Fastest IPTV & Debrid Hybrid Player for Android TV & FireStick",
  description:
    "Experience 0ms navigation latency, Room DB local-first caching, 4K HDR Debrid streaming, and zero buffering. Built specifically for high-end Leanback TV remote navigation.",
};

export const NAVIGATION_LINKS = [
  { name: "Features", href: "/#features" },
  { name: "Download", href: "/download" },
  { name: "Setup Guide", href: "/setup-guide" },
  { name: "Pricing", href: "/pricing" },
  { name: "Resellers", href: "/reseller" },
];

export const COMPARISON_DATA = [
  {
    feature: "0ms Navigation Latency (Skeleton UI)",
    dxPlay: true,
    tivimate: false,
    smarters: false,
    stremio: false,
    detail: "Optimistic UI with local Room DB indexing keeps UI instant even on FireStick.",
  },
  {
    feature: "Native Debrid Torrent Proxy (StremThru/Debridio)",
    dxPlay: true,
    tivimate: false,
    smarters: false,
    stremio: true,
    detail: "Stream high-bitrate 4K movies & series directly from cached torrents with zero buffering.",
  },
  {
    feature: "Xtream Codes + Live TV + Catchup",
    dxPlay: true,
    tivimate: true,
    smarters: true,
    stremio: false,
    detail: "Full IPTV integration with category management, multi-screen, and channel zapping.",
  },
  {
    feature: "Cloud Web Companion & QR Pairing",
    dxPlay: true,
    tivimate: false,
    smarters: false,
    stremio: true,
    detail: "Pair your TV with a simple 4-letter code from your smartphone. No tedious remote typing.",
  },
  {
    feature: "Software License Reseller Portal",
    dxPlay: true,
    tivimate: false,
    smarters: false,
    stremio: false,
    detail: "Wholesale license credits and instant automated customer TV device activation.",
  },
  {
    feature: "Automatic In-App OTA Updates",
    dxPlay: true,
    tivimate: true,
    smarters: false,
    stremio: false,
    detail: "Silent background update checks directly from Firebase cloud storage.",
  },
];

export const PRICING_PLANS = [
  {
    id: "trial",
    name: "24-Hour Free App Trial",
    price: "$0",
    period: "24 hours / 1 device",
    badge: "Free Test",
    description: "Test the player software on your FireStick or Android TV with your own playlist.",
    features: [
      "Full Media Player Software Access",
      "Connect Your Own Xtream Codes Server",
      "Connect Your Own Debrid Account",
      "0ms Skeleton Fast Navigation",
      "Smart EPG & Remote D-Pad Interface",
      "No payment or card required",
    ],
    cta: "Start Free App Trial",
    highlighted: false,
  },
  {
    id: "annual",
    name: "1-Year Software License",
    price: "$14.99",
    period: "per year / 1 device",
    badge: "Annual Pass",
    description: "12-month software license with full player features and free OTA updates.",
    features: [
      "1-Year Active App License",
      "Bring Your Own Playlist / Xtream Codes",
      "Native Debrid Proxy (StremThru/Debridio)",
      "Media3 Hardware Accelerated 4K Player",
      "Cloud Web Companion Pairing (/link)",
      "1 Year of Automated In-App Updates",
      "Standard Technical Support",
    ],
    cta: "Get 1-Year License",
    highlighted: false,
  },
  {
    id: "lifetime",
    name: "Lifetime Software License",
    price: "$29.99",
    period: "one-time payment / 1 device",
    badge: "Best Value • Pay Once",
    description: "Pay once and own the software forever. No recurring fees, lifetime free updates.",
    features: [
      "Permanent Lifetime App License",
      "Bring Your Own Playlist / Xtream Codes",
      "Native Debrid Proxy 4K HDR & Atmos",
      "Transfer License to New TV Device Anytime",
      "Lifetime Free Software Updates (OTA)",
      "0ms Local Room DB Caching Engine",
      "VIP Priority WhatsApp & Telegram Support",
    ],
    cta: "Get Lifetime License",
    highlighted: true,
  },
];

