#!/usr/bin/env bash
#
# Watches the device's AudioTrack pool for the "first frame freezes after three or four days"
# incident, and captures forensics AT THE MOMENT it starts going wrong.
#
# Why this exists: AudioFlinger allows 64 tracks per output thread. When the pool fills, the audio
# renderer cannot allocate a track, it throws right after the video's first frame renders, and the
# picture stops there — on Live, on resume, on fresh content — until the device is restarted. It was
# measured full (`64 Tracks of which 63 are active`, every one TERMINATED) with fifteen of the dead
# tracks belonging to this app's process.
#
# Why a recorder and not a test: the accumulation takes days. Zapping, hand-offs, browsing and player
# teardown were each measured and each gives its tracks back (see AudioTrackLeakStressTest), so
# whatever does this is neither frequent nor reproducible on demand. The only way left is to be
# watching when it happens.
#
# The watcher runs ON THE DEVICE under nohup, so it survives adb disconnects, laptop sleep and Wi-Fi
# drops — none of which a tethered `adb shell` loop would.
#
# Usage:
#   scripts/audio_track_watch.sh start [device]   # push + launch (safe to re-run; replaces)
#   scripts/audio_track_watch.sh status [device]  # is it alive, and the last few samples
#   scripts/audio_track_watch.sh fetch  [device]  # pull the log + every forensic snapshot
#   scripts/audio_track_watch.sh stop   [device]
#
# `device` defaults to $AUDIO_WATCH_DEVICE, then to the only attached device.

set -uo pipefail

# Git Bash rewrites anything that looks like a Unix path into a Windows one, which turns the
# device-side "/sdcard/..." into "C:/Program Files/Git/sdcard/..." and fails the push. Harmless
# elsewhere; this repo is developed on Windows.
export MSYS_NO_PATHCONV=1
export MSYS2_ARG_CONV_EXCL='*'

ADB="${ADB:-adb}"
PACKAGE="${AUDIO_WATCH_PACKAGE:-com.debridxtream.tv}"
DEVICE_DIR="/sdcard/audio_track_watch"
DEVICE_SCRIPT="$DEVICE_DIR/watch.sh"
LOG="$DEVICE_DIR/samples.log"
LOCAL_DIR="${AUDIO_WATCH_OUT:-docs/reports/audio_track_watch}"

# How often to sample, and the count at which a sample is worth a full forensic dump. Idle is 0 and
# active playback is 1, so five means something is being kept that should not be.
INTERVAL_SECONDS="${AUDIO_WATCH_INTERVAL:-300}"
ALERT_THRESHOLD="${AUDIO_WATCH_THRESHOLD:-5}"
# AudioFlinger allows 64 tracks per output thread; half of them held is already well past healthy
# (a quiet device sits at 3-5), so this catches the run-up rather than the crash.
POOL_ALERT_THRESHOLD="${AUDIO_WATCH_POOL_THRESHOLD:-32}"

DEVICE_ARG=""
if [ "${2:-}" != "" ]; then
    DEVICE_ARG="-s $2"
elif [ "${AUDIO_WATCH_DEVICE:-}" != "" ]; then
    DEVICE_ARG="-s $AUDIO_WATCH_DEVICE"
fi

adb_sh() { $ADB $DEVICE_ARG shell "$@"; }

write_device_script() {
    cat <<DEVICE_EOF
#!/system/bin/sh
# Generated by scripts/audio_track_watch.sh — do not edit on the device, it is overwritten on start.
DIR="$DEVICE_DIR"
LOG="$LOG"
PKG="$PACKAGE"
INTERVAL=$INTERVAL_SECONDS
THRESHOLD=$ALERT_THRESHOLD
POOL_THRESHOLD=$POOL_ALERT_THRESHOLD

# Own pid on disk: 'ps' on this platform shows the interpreter, not the script name, so grepping for
# watch.sh finds nothing even while it is plainly running.
echo \$\$ > "\$DIR/watch.pid"

# One forensic dump per escalation, not one per sample: the interesting moment is when the count
# first climbs past a level, and repeating it every five minutes would bury that in noise.
last_alert=0

while true; do
    now=\$(date '+%Y-%m-%d %H:%M:%S')
    pid=\$(pidof \$PKG)
    dump=\$(dumpsys media.audio_flinger 2>/dev/null)

    # Counting is table-aware and lives in count_tracks.awk — see the note there for why a plain
    # pattern over the whole dump cannot work.
    all=\$(echo "\$dump" | awk -v p="" -f "\$DIR/count_tracks.awk")
    if [ -n "\$pid" ]; then
        ours=\$(echo "\$dump" | awk -v p="\$pid" -f "\$DIR/count_tracks.awk")
    else
        ours=-1   # app not running: distinct from a genuine zero, so a gap is never read as healthy
    fi
    # The pool occupancy AudioFlinger reports itself — this is the number that hits 64 and freezes
    # playback, so it is the one the alert is really watching.
    peak=\$(echo "\$dump" | grep "Tracks of which" | sed 's/^ *//' | cut -d' ' -f1 | sort -rn | head -1)

    echo "\$now pid=\${pid:-none} ours=\$ours all=\$all peak=\${peak:-0}" >> \$LOG

    # Forensics the moment things start climbing. Two triggers, because the incident is the POOL
    # filling — whoever fills it. Watching only our own tracks would miss the run-up entirely if the
    # slots are going somewhere else, and that is exactly the question this is here to answer.
    level=\$ours
    [ "\${peak:-0}" -gt "\$level" ] && level=\$peak
    if { [ "\$ours" -ge "\$THRESHOLD" ] || [ "\${peak:-0}" -ge "\$POOL_THRESHOLD" ]; } &&
       [ "\$level" -gt "\$last_alert" ]; then
        last_alert=\$level
        stamp=\$(date '+%Y%m%d-%H%M%S')
        echo "\$now ALERT ours=\$ours peak=\$peak — captured \$stamp" >> \$LOG
        echo "\$dump" > "\$DIR/flinger-\$stamp-ours\$ours-peak\$peak.txt"
        logcat -d -v time > "\$DIR/logcat-\$stamp-ours\$ours-peak\$peak.txt" 2>/dev/null
    fi

    sleep \$INTERVAL
done
DEVICE_EOF
}

# Counts CURRENT AudioFlinger tracks, optionally for one client pid (-v p=<pid>; empty counts all).
#
# This has to be table-aware, and that is the whole trap in reading this dump: further down it
# carries a "Local log" of historical AT::add / AT::remove lines whose shape is identical to a live
# track row. Patterns matched against the whole dump counted that history as current tracks and
# reported 8, then 47, then 57, on a device that was holding two. Only rows between a
# "Tracks of which" header and the first line that is not a row are real.
#
# The row layout also varies by thread — a playback table has a leading Name column, a record table
# does not — so the client is read as the field AFTER yes/no rather than by column number.
#
# Quoted heredoc on purpose: nothing in here is for the host shell to expand.
write_awk_program() {
    cat <<'AWK_EOF'
/Tracks of which/ { intable = 1; next }
intable {
    if ($0 ~ /Active +Client/) next
    matched = 0
    for (i = 1; i < NF; i++) {
        if ($i == "yes" || $i == "no") {
            # Concatenating "" forces a STRING compare. Android ships one-true-awk, which tries to
            # compare numerically when both sides look like numbers and dies with
            # "illegal arithmetic operator" partway through this dump.
            client = $(i + 1) ""
            want = p ""
            if (length(want) == 0 || client == want) n++
            matched = 1
            break
        }
    }
    if (matched == 0) intable = 0
}
END { print n + 0 }
AWK_EOF
}

cmd_start() {
    adb_sh "mkdir -p $DEVICE_DIR" >/dev/null 2>&1
    cmd_stop >/dev/null 2>&1

    # Relative, and in the working directory on purpose: with path conversion off (see the top of
    # this file) a Windows adb.exe cannot resolve an MSYS "/tmp/..." path, and with it on it mangles
    # the device path instead. A relative one is the only spelling both ends agree on.
    local tmp=".audio_track_watch.push.tmp"
    write_device_script > "$tmp"
    $ADB $DEVICE_ARG push "$tmp" "$DEVICE_SCRIPT" >/dev/null 2>&1 ||
        { echo "push failed"; rm -f "$tmp"; exit 1; }
    write_awk_program > "$tmp"
    $ADB $DEVICE_ARG push "$tmp" "$DEVICE_DIR/count_tracks.awk" >/dev/null 2>&1 ||
        { echo "push failed"; rm -f "$tmp"; exit 1; }
    rm -f "$tmp"
    adb_sh "chmod 755 $DEVICE_SCRIPT" >/dev/null 2>&1

    # nohup + a detached shell: the watcher must outlive this adb connection.
    adb_sh "nohup sh $DEVICE_SCRIPT >/dev/null 2>&1 &" >/dev/null 2>&1
    sleep 3

    if is_alive; then
        echo "watching every ${INTERVAL_SECONDS}s; forensic dump at ours >= ${ALERT_THRESHOLD}"
        echo "log: $LOG"
    else
        echo "failed to start — check '$ADB $DEVICE_ARG shell sh $DEVICE_SCRIPT' by hand"
        exit 1
    fi
}

# Liveness by pid file, not by name: see the note in the device script.
is_alive() {
    local pid
    pid="$(adb_sh "cat $DEVICE_DIR/watch.pid 2>/dev/null" | tr -d '\r')"
    [ -n "$pid" ] || return 1
    adb_sh "kill -0 $pid 2>/dev/null && echo yes" | tr -d '\r' | grep -q yes
}

cmd_status() {
    if is_alive; then echo "watcher: RUNNING"; else echo "watcher: NOT running"; fi
    echo "samples: $(adb_sh "wc -l < $LOG 2>/dev/null" | tr -d '\r')"
    echo "alerts:  $(adb_sh "grep -c ALERT $LOG 2>/dev/null" | tr -d '\r')"
    echo "--- last 10 ---"
    adb_sh "tail -10 $LOG 2>/dev/null"
}

cmd_fetch() {
    mkdir -p "$LOCAL_DIR"
    $ADB $DEVICE_ARG pull "$DEVICE_DIR" "$LOCAL_DIR" >/dev/null 2>&1
    echo "pulled to $LOCAL_DIR/"

    local log
    log="$(find "$LOCAL_DIR" -name samples.log 2>/dev/null | head -1)"
    [ -n "$log" ] || { echo "(no samples pulled)"; return; }

    # -1 means the app was not running, which is not a track count — excluded so it cannot be
    # mistaken for a reading, and so the negative sign cannot poison the sort.
    echo "--- highest 'ours' recorded (-1 samples are 'app not running') ---"
    sed -n 's/.*ours=\([0-9][0-9]*\).*/\1/p' "$log" | sort -rn | head -1
    echo "--- highest pool occupancy recorded (64 is the limit that freezes playback) ---"
    sed -n 's/.*peak=\([0-9][0-9]*\).*/\1/p' "$log" | sort -rn | head -1
    echo "--- alerts ---"
    grep ALERT "$log" 2>/dev/null || echo "(none — nothing has climbed yet)"
}

cmd_stop() {
    adb_sh "p=\$(cat $DEVICE_DIR/watch.pid 2>/dev/null); [ -n \"\$p\" ] && kill \$p; rm -f $DEVICE_DIR/watch.pid" >/dev/null 2>&1
    echo "stopped"
}

case "${1:-}" in
    start)  cmd_start ;;
    status) cmd_status ;;
    fetch)  cmd_fetch ;;
    stop)   cmd_stop ;;
    *)      sed -n '3,30p' "$0"; exit 1 ;;
esac
