#!/usr/bin/env bash
#
# One-time release signing setup: generate the release key, read its certificate SHA-256, and write
# keystore.properties so the app's anti-repack self-check turns on.
#
# WHY THIS MATTERS. Until keystore.properties exists, `EXPECTED_SIGNING_SHA256` is empty and
# `AppIntegrity.isTrustedSignature()` returns true unconditionally — so a repacked, re-signed build
# passes the check today. The code for it has been shipped for a while; only the key is missing.
#
# WHAT IT ACTUALLY BUYS. The signature check gates PREMIUM (`isPremiumCached`), not basic
# entitlement, so a repack loses debrid but keeps plain IPTV. That is the existing fail-open design,
# not an oversight. This raises the bar; it is not the lock. The lock is keeping what the app needs
# (provider credentials) on the server and handing it only to a licensed device.
#
# WHY IT ASKS YOU FOR THE PASSWORDS. The release key is the most important secret in the project: if
# it is lost, this app can never ship an in-place update again, ever. Passwords are typed straight
# into keytool here and are never printed, logged, or passed on a command line where `ps` could see
# them.
#
# Usage:  bash scripts/setup_release_signing.sh
#
# AFTER RUNNING:
#   1. BACK UP the .jks and both passwords somewhere you will still have in five years.
#   2. Every device with the current debug-signed build must be UNINSTALLED and reinstalled once —
#      Android refuses an in-place update when the signing certificate changes.

set -uo pipefail

KEYSTORE_FILE="${KEYSTORE_FILE:-debridxtream-release.jks}"
KEY_ALIAS="${KEY_ALIAS:-debridxtream}"
PROPS_FILE="keystore.properties"

die() { echo "ERROR: $*" >&2; exit 1; }

command -v keytool >/dev/null 2>&1 || die "keytool not found — it ships with the JDK; make sure JAVA_HOME/bin is on PATH."

# Refuse to touch an existing key. Overwriting it would silently destroy the ability to update every
# install already out there, and that is not something a script should be able to do by accident.
[ -e "$KEYSTORE_FILE" ] && die "$KEYSTORE_FILE already exists. Refusing to overwrite a release key. Delete it deliberately if you really mean to start over."
[ -e "$PROPS_FILE" ] && die "$PROPS_FILE already exists. Refusing to overwrite it."

echo "This creates the RELEASE signing key for the app."
echo "Keystore: $KEYSTORE_FILE   alias: $KEY_ALIAS"
echo
echo "Choose a password you will not lose. Losing it means no future updates for this app."
printf "Keystore password: "
read -rs STORE_PASS; echo
[ ${#STORE_PASS} -ge 6 ] || die "keytool requires at least 6 characters."
printf "Repeat: "
read -rs STORE_PASS_2; echo
[ "$STORE_PASS" = "$STORE_PASS_2" ] || die "passwords did not match."

# One password for both, which is what -destkeypass would end up doing anyway, and one less secret to
# lose. keytool reads them from stdin so they never appear in the process list.
printf '%s\n%s\n' "$STORE_PASS" "$STORE_PASS" | keytool -genkeypair -v \
    -keystore "$KEYSTORE_FILE" \
    -alias "$KEY_ALIAS" \
    -keyalg RSA -keysize 2048 -validity 10000 \
    -dname "CN=DebridXtream, OU=TV, O=DebridXtream, C=DE" \
    >/dev/null 2>&1 || die "keytool failed to create the keystore."

echo "Key created."

# Uppercase hex, colons stripped — the exact shape BuildConfig.EXPECTED_SIGNING_SHA256 is compared against.
SHA256="$(printf '%s\n' "$STORE_PASS" | keytool -list -v -keystore "$KEYSTORE_FILE" -alias "$KEY_ALIAS" 2>/dev/null \
    | grep -m1 'SHA256:' | sed 's/.*SHA256: *//' | tr -d ': ' | tr '[:lower:]' '[:upper:]')"
[ -n "$SHA256" ] || die "created the keystore but could not read its SHA-256. Nothing was written to $PROPS_FILE."

cat > "$PROPS_FILE" <<PROPS
# Generated by scripts/setup_release_signing.sh — git-ignored, never commit this.
storeFile=../$KEYSTORE_FILE
storePassword=$STORE_PASS
keyAlias=$KEY_ALIAS
keyPassword=$STORE_PASS

# RELEASE cert SHA-256, uppercase hex, no colons. Empty = self-check disabled.
EXPECTED_SIGNING_SHA256=$SHA256
PROPS

unset STORE_PASS STORE_PASS_2

echo
echo "Wrote $PROPS_FILE   (SHA-256: ${SHA256:0:16}…)"
echo
echo "NOW DO THESE TWO THINGS:"
echo "  1. Back up $KEYSTORE_FILE and the password. Lose them and this app can never be updated again."
echo "  2. Build a release APK and reinstall it ONCE on every device — an in-place update over the"
echo "     current debug-signed build will be rejected, because the signing certificate changed:"
echo "         ./gradlew :app:assembleRelease"
echo "         adb uninstall com.debridxtream.tv && adb install app/build/outputs/apk/release/app-release.apk"
